# ===============================================================
# 日常任务设置
# ===============================================================

# 矿洞设置
# 副本默认开启 第一层（简单）
矿洞:
  floor: 1 # 1、2、3、4、5分别对应第一~第五层
  mode: 1 # 1、2、3分别对应简单、普通、困难

# 历练设置
# 依次按照id乐斗BOSS，每个BOSS最多乐斗3次
# 活力不足时不会自动使用活力药水
历练:
  - 6114 # 摩云山 韦小宝碎片
  - 6134 # 洞庭湖 扫地僧碎片
  - 6154 # 苍莽山 鹤笔翁碎片
  - 6034 # 林松郊外 令狐冲碎片
  - 6054 # 林松城 丁春秋碎片
  - 6074 # 东海龙宫 丘处机碎片
  - 6094 # 踏云镇 小龙女碎片
  - 6174 # 玉龙湿地 韦一笑碎片
  - 6194 # 玉龙雪山 赵敏碎片

# 会武设置
# 周五会武商店兑换
# 周一~周三试炼场挑战次数不足时会自动兑换试炼书*1，所以不需添加
会武:
  真黄金卷轴:
    id: 1263
    number: 20 # 兑换20个
  修为丹:
    id: 1264
    number: 0 # 兑换0个

# 背包设置
# 背包使用指定物品（拥有数量是使用次数最大值）
# 物品支持全字、部分名称及正则匹配
背包:
  - 盒 # 匹配仙侠盲盒、周年壕气礼盒...
  - 箱 # 匹配资源补给箱、魂珠碎片宝箱...
  - 锦囊 # 匹配惊喜锦囊、武神坛银锦囊...
  - 信物 # 匹配蔡八斗的信物、吕青橙的信物...
  - 包 # 匹配贡献小笼包、贡献叉烧包...
  - 勋章 # 匹配巅峰之战一等勋章、巅峰之战二等勋章...
  - 神来拳套\(赠\)
  - 大力丸
  - 活血散
  - 迅捷珠
  - 风之息
  - 减伤药水
  - 翡翠银戒
  - 阅历羊皮卷

# 神匠坊设置
# 符石分解默认 I类
神匠坊:
  - 6161 # 破坏·幽月I
  - 6160 # 闪耀·银光I
  - 6159 # 终结·焱炎I
  - 6158 # 洞悉·紫晶I
  # - 6157 # 破坏·流风II
  # - 6156 # 闪耀·流风II
  # - 6155 # 破坏·幽月II
  # - 6154 # 闪耀·幽月II
  # - 6153 # 破坏·银光II
  # - 6152 # 闪耀·银光II
  # - 6151 # 洞悉·焱炎II
  # - 6150 # 洞悉·焱炎II
  # - 6149 # 终结·苍玉II
  # - 6148 # 洞悉·苍玉II
  # - 6147 # 终结·紫晶II
  # - 6146 # 洞悉·紫晶II
  # - 6145 # 破坏·暴风III
  # - 6144 # 闪耀·暴风III
  # - 6143 # 破坏·狂风III
  # - 6142 # 闪耀·狂风III
  # - 6141 # 破坏·霸风III
  # - 6140 # 闪耀·霸风III
  # - 6139 # 破坏·流风III
  # - 6138 # 闪耀·流风III
  # - 6137 # 破坏·灵月III
  # - 6136 # 闪耀·灵月III
  # - 6135 # 破坏·清月III
  # - 6134 # 闪耀·清月III
  # - 6133 # 破坏·锦月III
  # - 6132 # 闪耀·锦月III
  # - 6131 # 破坏·雪月III
  # - 6130 # 闪耀·雪月III
  # - 6129 # 破坏·幽月III
  # - 6128 # 闪耀·幽月III
  # - 6127 # 破坏·银光III
  # - 6126 # 闪耀·银光III
  # - 6125 # 终结·异炎III
  # - 6124 # 洞悉·异炎III
  # - 6123 # 终结·焱炎III
  # - 6122 # 洞悉·焱炎III
  # - 6121 # 终结·烟晶III
  # - 6120 # 洞悉·烟晶III
  # - 6119 # 终结·紫晶III
  # - 6118 # 洞悉·紫晶III

# 竞技场设置
竞技场: false # 是否每天兑换10个河图洛书

# 华山论剑设置
# 每月26号华山论剑荣誉兑换
华山论剑:
  钻石:
    id: 6857
    number: 375 # 兑换375个
  侠士修身录:
    id: 6347
    number: 100 # 兑换100个
  侠士手记:
    id: 6348
    number: 80 # 兑换80个
  重出江湖令:
    id: 6349
    number: 0 # 兑换0个
  斗神符:
    id: 3090
    number: 0 # 兑换0个

# 问鼎天下设置
# 周六淘汰赛助威、周日排名赛助威
问鼎天下:
  # 傲龙づ族℃：96690
  # 神阁☆圣域：82494
  淘汰赛: 96690
  排名赛: 96690

# 帮派商会设置
# 指定交易及兑换物品
# 物品支持全字、部分名称及正则匹配
帮派商会:
  交易会所:
    - 体力 # 匹配真体力、大体力、小体力等含有体力的物品
    - 经验 # 匹配经验药水、经验木筒等含有经验的物品
    - 悟性丹\*20 # 匹配悟性丹*20
    - 百炼钢 # 匹配百炼钢
    # - 凤凰羽毛 # 匹配凤凰羽毛
  兑换商店:
    - V碎片 # 匹配xx.xxV碎片*1

# 武林盟主设置
# 默认报名 黄金赛场
# 黄金赛场 1 要求最低战力2000
# 白银赛场 2 要求最低战力1000
# 青铜赛场 3 要求最低战力200
武林盟主: 1

# 江湖长梦设置
# 每天执行
江湖长梦:
  柒承的忙碌日常: 2 # 开启副本次数

# 我的帮派设置
# 帮派守护神供奉，每个物品最多供奉5次
我的帮派:
  - 3043 # 被动经验药水
  - 3014 # 经验药水
  - 3001 # 小体力
  - 3003 # 大体力
  - 3028 # 神来拳套
  - 3074 # 追魂锁链
  - 3089 # 还魂丹
  - 3100 # 还童卷轴
  - 3871 # 百炼钢
  - 5391 # 佣兵天赋丹

# 深渊之潮设置
深渊之潮:
  深渊秘境:
    # 1 崎岖斗界
    # 2 魂渡桥
    # 3 须臾之河
    # 4 曲镜空洞
    # 5 光影迷界
    # 6 吞厄源头
    # 7 渊秘祭坛
    # 8 古帝遗迹
    id: 1
    exchange: false # 是否兑换一次副本次数（第一、二轮各兑换一次）
  许愿帮铺:
    # 周四兑换
    气魄之书:
      id: 5
      number: 200 # 兑换200个
    力魄之书:
      id: 6
      number: 200 # 兑换200个
    精魄之书:
      id: 7
      number: 200 # 兑换200个
    英魄之书:
      id: 8
      number: 200 # 兑换200个
    中枢之书:
      id: 9
      number: 200 # 兑换200个
    天冲之书:
      id: 10
      number: 200 # 兑换200个
    灵慧之书:
      id: 11
      number: 200 # 兑换200个
    佣兵天赋丹:
      id: 12
      number: 0 # 兑换0个
    许愿卡:
      id: 13
      number: 0 # 兑换0个
    五星许愿卡碎片:
      id: 14
      number: 0 # 0个
    豆油队长碎片:
      id: 15
      number: 88 # 兑换88个
    定海制作书:
      id: 16
      number: 1 # 兑换1个

# 时空遗迹设置
时空遗迹:
  异兽洞窟:
    # 优先扫荡否则挑战
    - 5 # 异兽母巢
    - 4 # 异兽元帅
    - 3 # 异兽将领
    - 2 # 异兽战士
    - 1 # 异兽幼崽
  遗迹商店:
    1: # 特惠区
      日引石:
        id: 1
        number: 100 # 兑换100个
      月引石:
        id: 2
        number: 100 # 兑换100个
      星引石:
        id: 3
        number: 100 # 兑换100个
      舆图:
        id: 4
        number: 40 # 兑换40个
    2: # 售卖区
      日引石:
        id: 5
        number: 50 # 兑换50个
      月引石:
        id: 6
        number: 50 # 兑换50个
      星引石:
        id: 7
        number: 50 # 兑换50个
      舆图:
        id: 8
        number: 20 # 兑换20个

# 门派邀请赛设置
# 周一、周二门派邀请赛商店兑换
# 周三~周日自动兑换门派战书*1，所以不需添加
门派邀请赛:
  炼气石:
    id: 1246
    number: 20 # 兑换20个
  门派强化书:
    id: 1247
    number: 10 # 兑换10个
  门派高香:
    id: 1248
    number: 0 # 兑换0个
  门派引荐书:
    id: 1250
    number: 0 # 兑换0个

# ===============================================================
# 周活动设置
# ===============================================================

# 登录商店设置
# 周四兑换
登录商店: 1224
# 1221 中体力*1
# 1222 真体力*1
# 1223 黄金卷轴*1
# 1224 孙子兵法*1
# 1225 武穆遗书*1
# 1226 神秘精华*1
# 1227 神兵原石*1
# 1228 软猥金丝*1
# 1229 凤凰羽毛*1
# 1230 潜能果实*1
# 1231 上古玉髓*1
# 1232 奔流气息*1

# 生肖福卡设置
# 福卡分享给指定好友QQ（比如自己小号），默认不分享
生肖福卡: null

# 企鹅吉利兑设置
# 截止日前一天兑换
企鹅吉利兑:
  玄铁令: 20 # 兑换20个
  熔炼乌金: 100 # 兑换100个
  V级万能碎片: 25 # 兑换25个
  挑战书: 30 # 兑换30个
